on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          GOOS=darwin go build -o dataplaneapi-mac -v .
          GOOS=linux GOARCH=amd64 go build -o dataplaneapi-linux64 -v .
          GOOS=freebsd GOARCH=amd64 go build -o dataplaneapi-freebsd -v .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Mac artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dataplaneapi-mac
          path: dataplaneapi-mac

      - name: Upload Linux artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dataplaneapi-linux64
          path: dataplaneapi-linux64

      - name: Upload FreeBSD artifacts   
        uses: actions/upload-artifact@v1
        with:
          name: dataplaneapi-freebsd
          path: dataplaneapi-freebsd


